# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1e2030"

# Main text color
theme[main_fg]="#cad3f5"

# Title color for boxes
theme[title]="#cad3f5"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#8aadf4"

# Background color of selected item in processes box
theme[selected_bg]="#363a4f"

# Foreground color of selected item in processes box
theme[selected_fg]="#c6a0f6"

# Color of inactive/disabled text
theme[inactive_fg]="#5b6078"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#b8c0e0"

# Background color of the percentage meters
theme[meter_bg]="#363a4f"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#b8c0e0"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#f5bde6"
theme[mem_box]="#a6da95"
theme[net_box]="#ed8796"
theme[proc_box]="#c6a0f6"

# Box divider line and small boxes line color
theme[div_line]="#5b6078"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#a6da95"
theme[temp_mid]="#eed49f"
theme[temp_end]="#ed8796"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#91d7e3"
theme[cpu_mid]="#8aadf4"
theme[cpu_end]="#f5bde6"

# Mem/Disk free meter
theme[free_start]="#f5bde6"
theme[free_mid]="#8aadf4"
theme[free_end]="#91d7e3"

# Mem/Disk cached meter
theme[cached_start]="#8aadf4"
theme[cached_mid]="#91d7e3"
theme[cached_end]="#f5bde6"

# Mem/Disk available meter
theme[available_start]="#eed49f"
theme[available_mid]="#ed8796"
theme[available_end]="#ed8796"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#a6da95"
theme[used_mid]="#91d7e3"
theme[used_end]="#8aadf4"

# Download graph colors
theme[download_start]="#eed49f"
theme[download_mid]="#ed8796"
theme[download_end]="#ed8796"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#a6da95"
theme[upload_mid]="#91d7e3"
theme[upload_end]="#8aadf4"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#91d7e3"
theme[process_mid]="#8aadf4"
theme[process_end]="#f5bde6"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#1e2030"
theme[gradient_color_1]="#363a4f"
theme[gradient_color_2]="#363a4f"
theme[gradient_color_3]="#5b6078"
theme[gradient_color_4]="#6e738d"
theme[gradient_color_5]="#cad3f5"
theme[gradient_color_6]="#b8c0e0"
theme[gradient_color_7]="#cad3f5"
