mode = "dark"

accent = "#8aadf4"
selection = "#363a4f"
muted = "#5b6078"

background = "#24273a"
dark_background = "#1e2030"
darker_background = "#181926"
lighter_background = "#363a4f"

foreground = "#cad3f5"
dark_foreground = "#6e738d"
light_foreground = "#b8c0e0"
bright_foreground = "#cad3f5"

red = "#ed8796"
yellow = "#eed49f"
orange = "#f5a97f"
green = "#a6da95"
cyan = "#91d7e3"
blue = "#8aadf4"
magenta = "#f5bde6"
brown = "#ee99a0"

bright_red = "#ed8796"
bright_yellow = "#eed49f"
bright_green = "#a6da95"
bright_cyan = "#91d7e3"
bright_blue = "#8aadf4"
bright_magenta = "#f5bde6"

hyprland_active_border = "#8373ab"
hyprland_inactive_border = "#8373ab80"
