background = #24273a
foreground = #cad3f5
cursor-color = #cad3f5
selection-background = #363a4f
selection-foreground = #cad3f5

palette = 0=#24273a
palette = 1=#ed8796
palette = 2=#a6da95
palette = 3=#eed49f
palette = 4=#8aadf4
palette = 5=#f5bde6
palette = 6=#91d7e3
palette = 7=#cad3f5
palette = 8=#5b6078
palette = 9=#ed8796
palette = 10=#a6da95
palette = 11=#eed49f
palette = 12=#8aadf4
palette = 13=#f5bde6
palette = 14=#91d7e3
palette = 15=#cad3f5

window-padding-x = 8
window-padding-y = 8
