foreground #cad3f5
background #24273a
selection_foreground #cad3f5
selection_background #363a4f

cursor #cad3f5
cursor_text_color #24273a

active_border_color #8aadf4
active_tab_background #8aadf4

color0 #24273a
color1 #ed8796
color2 #a6da95
color3 #eed49f
color4 #8aadf4
color5 #f5bde6
color6 #91d7e3
color7 #cad3f5
color8 #5b6078
color9 #ed8796
color10 #a6da95
color11 #eed49f
color12 #8aadf4
color13 #f5bde6
color14 #91d7e3
color15 #cad3f5

window_padding_width 8
