"$schema" = "https://starship.rs/config-schema.json"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold #8373ab)"
error_symbol = "[✗](bold #ed8796)"

[username]
format = "[$user]($style) "
style = "bold #a6da95"

[hostname]
format = "@[$hostname]($style) "
style = "bold #f5a97f"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold #8aadf4"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold #c6a0f6"

[git_status]
format = '([\[$all_status\]]($style))'
style = "#a6da95"

[python]
format = "[${symbol}${pyenv_prefix}(${version})(${virtualenv})]($style) "
style = "#8aadf4"

[nodejs]
format = "[$symbol($version)]($style) "
style = "#a6da95"

[rust]
format = "[$symbol($version)]($style) "
style = "#f5a97f"

[golang]
format = "[$symbol($version)]($style) "
style = "#8aadf4"

[cmd_duration]
format = "[$duration]($style) "
style = "#eed49f"

[line_break]
disabled = false
